options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages({library(data.table);library(Matrix);library(Seurat);library(ggplot2)})
script_arg<-grep("^--file=",commandArgs(),value=TRUE);script_dir<-dirname(normalizePath(sub("^--file=","",script_arg[[1L]])))
source(file.path(script_dir,"_diagnostics_v2_common.R"));z<-read_diagnostics_config();cfg<-z$cfg
data_root<-normalizePath(cfg$project$data_root,winslash="/",mustWork=TRUE);v4<-file.path(data_root,"diagnostics_v4_cross_dataset_validation");v5<-file.path(data_root,"diagnostics_v5_final_calibration");dir.create(v5,recursive=TRUE,showWarnings=FALSE)
replace_generated<-"--replace-generated-output"%in%commandArgs(trailingOnly=TRUE);out<-file.path(v5,"GSE147082_cluster6_subcluster_markers.csv");if(file.exists(out)&&!replace_generated)stop("Output exists: ",out)
seed<-as.integer(cfg$project$random_seed%||%20260718L);set.seed(seed)
a<-fread(file.path(v4,"GSE147082_refined","refined_cell_assignments.csv.gz"));c4<-fread(file.path(v4,"GSE147082_refined","refined_cluster_annotation.csv"))
obj<-readRDS(file.path(data_root,"GSE147082","objects","GSE147082_preannotation.rds"));counts<-SeuratObject::LayerData(obj,assay="RNA",layer="counts")[,a$cell_id,drop=FALSE]
c6cells<-a[final_cluster==6,cell_id];s<-CreateSeuratObject(counts[,c6cells,drop=FALSE],min.cells=0,min.features=0);s<-NormalizeData(s,verbose=FALSE);s<-FindVariableFeatures(s,nfeatures=2000,verbose=FALSE);s<-ScaleData(s,features=VariableFeatures(s),verbose=FALSE);s<-RunPCA(s,npcs=30,verbose=FALSE);s<-FindNeighbors(s,dims=1:20,verbose=FALSE);s<-FindClusters(s,resolution=.25,random.seed=seed,verbose=FALSE)
markers<-FindAllMarkers(s,only.pos=TRUE,test.use="wilcox",min.pct=.2,logfc.threshold=.25,return.thresh=1,verbose=FALSE);markers<-as.data.table(markers,keep.rownames=FALSE);if(!"gene"%in%names(markers))markers[,gene:=rownames(markers)];if("avg_logFC"%in%names(markers)&&!"avg_log2FC"%in%names(markers))setnames(markers,"avg_logFC","avg_log2FC");markers<-markers[p_val_adj<.05&avg_log2FC>.25&pct.1>=.2];markers[,`:=`(dataset_id="GSE147082",parent_cluster="6",subcluster=as.character(cluster))];fwrite(markers,out,na="NA")
d<-SeuratObject::LayerData(s,assay="RNA",layer="data");module<-function(g)Matrix::colMeans(d[intersect(g,rownames(d)),,drop=FALSE]);programs<-list(CD3=c("CD3D","CD3E","TRBC1","TRBC2","CD2"),gamma_delta=c("TRDC","TRGC1","TRGC2"),NK_cytotoxic=c("NKG7","GNLY","KLRD1","XCL1","XCL2","PRF1"),effector=c("FGFBP2","GNLY","GZMB","PRF1","CCL5","NKG7"),GZMK_memory=c("GZMK","IL7R","LTB","MAL","TCF7","CCR7"),cycling=c("MKI67","TOP2A","UBE2C","CENPF"),stress=c("FOS","JUN","JUNB","HSPA1A","HSPA1B","ATF3"))
md<-data.table(cell_id=colnames(s),subcluster=as.character(Idents(s)));for(nm in names(programs))md[[paste0(nm,"_program")]]<-module(programs[[nm]])
top<-markers[order(subcluster,-avg_log2FC),.(top20_real_differential_markers=paste(head(gene,20),collapse=";")),by=subcluster]
ann<-md[,c(list(n_cells=.N,n_samples=uniqueN(a$sample_id[match(cell_id,a$cell_id)]),dominant_sample_fraction=max(table(a$sample_id[match(cell_id,a$cell_id)]))/.N),lapply(.SD,mean)),by=subcluster,.SDcols=paste0(names(programs),"_program")];ann<-merge(ann,top,by="subcluster",all.x=TRUE)
ann[,initial_supported_label:=fcase(gamma_delta_program>=.30,"Gamma_delta_T",NK_cytotoxic_program>CD3_program*1.25,"NKT_like_cytotoxic",effector_program>GZMK_memory_program*1.25,"CD8_effector_T",GZMK_memory_program>=effector_program*.8,"CD8_GZMK_T",default="Cytotoxic_T")]
ann[,final_annotation:=initial_supported_label]
ann[initial_supported_label=="CD8_effector_T"&cycling_program>=.75,final_annotation:="Cycling_CD8_effector_T"]
cyt<-ann[initial_supported_label!="Gamma_delta_T"]
merged<-FALSE
if(nrow(cyt)>1&&uniqueN(ann[subcluster%in%cyt$subcluster,final_annotation])==1){merged<-TRUE;ann[subcluster%in%cyt$subcluster,final_annotation:="Cytotoxic_T_merged"]}
ann[,merge_decision:=ifelse(merged&initial_supported_label!="Gamma_delta_T","MERGED_SIMILAR_CYTOTOXIC_T","KEPT_DISTINCT_BY_MARKER_PROGRAM")]
fwrite(ann,file.path(v5,"GSE147082_cluster6_subcluster_annotation.csv"),na="NA")

# PT-2834 patient-internal chromosome-window CNV-like sensitivity.
pt<-"PT-2834";ptcells<-a[patient_id==pt,cell_id];ptcounts<-counts[,ptcells,drop=FALSE];ptobj<-CreateSeuratObject(ptcounts,min.cells=0,min.features=0);ptobj<-NormalizeData(ptobj,verbose=FALSE);ptdata<-SeuratObject::LayerData(ptobj,assay="RNA",layer="data")
immune_types<-c("T_cell","B_cell","Macrophage","pDC","Mast","Cytotoxic_T","Gamma_delta_T");refcells<-a[patient_id==pt&final_cell_type%in%immune_types,cell_id];epicells<-a[patient_id==pt&final_cell_type=="Epithelial",cell_id];if(length(refcells)<10||length(epicells)<10)stop("Insufficient PT-2834 immune reference or epithelial cells")
refmean<-Matrix::rowMeans(ptdata[,refcells,drop=FALSE]);groups<-list(cluster_4=a[patient_id==pt&final_cluster==4,cell_id],cluster_7=a[patient_id==pt&final_cluster==7,cell_id],broad_epithelial=epicells)
refpath<-"D:/TEMP/ucsc_hg38_refGene.txt.gz";if(!file.exists(refpath))utils::download.file("https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz",refpath,mode="wb",quiet=TRUE,timeout=300)
rg<-fread(refpath,header=FALSE,select=c(3,5,6,13),showProgress=FALSE);setnames(rg,c("chrom","start","end","symbol"));rg<-rg[chrom%chin%paste0("chr",c(1:22,"X")),.(chrom=chrom[1],position=as.integer(median((start+end)/2))),by=symbol]
go<-merge(data.table(gene=rownames(ptdata),symbol=toupper(rownames(ptdata))),rg[,.(symbol=toupper(symbol),chrom,position)],by="symbol");go[,chr_order:=match(chrom,paste0("chr",c(1:22,"X")))];setorder(go,chr_order,position)
smooth<-function(cells){v<-Matrix::rowMeans(ptdata[,cells,drop=FALSE])-refmean;x<-copy(go);x[,value:=v[match(gene,rownames(ptdata))]];x<-x[is.finite(value)];x[,smooth:=if(.N>=51)runmed(value,k=min(101L,if(.N%%2L).N else .N-1L),endrule="median")else value,by=chrom];x[,genome_index:=.I];x}
prof<-lapply(groups,smooth);epi<-prof$broad_epithelial$smooth
sens<-rbindlist(lapply(names(prof),function(nm){x<-prof[[nm]];data.table(patient_id=pt,group=nm,n_cells=length(groups[[nm]]),method="exploratory_patient_internal_cnv_like",n_ordered_genes=nrow(x),cnv_intensity=mean(abs(x$smooth)),correlation_to_broad_epithelial=cor(x$smooth,epi,use="complete.obs"))}))
epiint<-sens[group=="broad_epithelial",cnv_intensity];sens[,cnv_intensity_ratio_to_epithelial:=cnv_intensity/epiint]
sens[,interpretation:=fcase(group=="cluster_4"&cnv_intensity_ratio_to_epithelial>=.75&correlation_to_broad_epithelial>=.5,"Malignant_mesenchymal_candidate",group=="cluster_4"&correlation_to_broad_epithelial<.5,"Mesenchymal_stromal_candidate",group=="cluster_4","Unresolved_mesenchymal_candidate",group=="cluster_7","COL2A1_positive_chondrocyte_like_fibroblast_candidate",default="broad_Epithelial_reference_not_uniformly_CNV_confirmed")]
fwrite(sens,file.path(v5,"GSE147082_PT2834_target_cluster_cnv_sensitivity.csv"),na="NA")
plotdt<-rbindlist(lapply(names(prof),function(nm){x<-prof[[nm]][seq(1,.N,by=25)];x[,group:=nm];x}));p<-ggplot(plotdt,aes(genome_index,smooth,color=group))+geom_line(linewidth=.45,alpha=.85)+theme_bw()+labs(title="PT-2834 patient-internal CNV-like sensitivity",subtitle="Exploratory chromosome-window expression deviation; broad Epithelial is not uniformly confirmed malignant",x="ordered genomic position",y="smoothed deviation")
ggsave(file.path(v5,"04_GSE147082_PT2834_target_cluster_cnv_plot.png"),p,width=11,height=5,dpi=180)
frozen<-copy(c4);frozen[cluster==4,`:=`(final_cell_type=sens[group=="cluster_4",interpretation],cell_subtype=sens[group=="cluster_4",interpretation],annotation_status="REVIEW_PATIENT_ENRICHED",annotation_confidence="Review")];frozen[cluster==7,`:=`(final_cell_type="COL2A1_positive_chondrocyte_like_fibroblast_candidate",cell_subtype="COL2A1_positive_chondrocyte_like_fibroblast_candidate")];frozen[cluster==6,`:=`(final_cell_type=if(merged)"Cytotoxic_T_merged_and_Gamma_delta_T"else paste(unique(ann$final_annotation),collapse=";"),cell_subtype=paste(unique(ann$final_annotation),collapse=";"),annotation_status="REVIEW_AMBIGUOUS",annotation_confidence="Review")]
fwrite(frozen,file.path(v5,"GSE147082_refined_annotation_v2.csv"),na="NA")
writeLines(c("# GSE147082 final targeted calibration","",paste0("- Cluster 6 decision: ",if(merged)"two marker-similar cytotoxic-T subclusters merged; gamma-delta T retained separately"else paste(unique(ann$final_annotation),collapse="; ")),paste0("- Cluster 4 PT-2834 patient-internal CNV-like result: ",sens[group=="cluster_4",interpretation]),paste0("- Cluster 7: ",sens[group=="cluster_7",interpretation]),"- Method is exploratory_patient_internal_cnv_like, not full inferCNV.","- Broad Epithelial is used as an expression/CNV-like comparison and is not called uniformly confirmed malignant."),file.path(v5,"GSE147082_targeted_calibration_summary.md"))
message("GSE147082 cluster 6 and PT-2834 CNV sensitivity complete")
