options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages(library(data.table))
script_arg<-grep("^--file=",commandArgs(),value=TRUE);script_dir<-dirname(normalizePath(sub("^--file=","",script_arg[[1L]])))
source(file.path(script_dir,"_diagnostics_v2_common.R"));z<-read_diagnostics_config();cfg<-z$cfg
data_root<-normalizePath(cfg$project$data_root,winslash="/",mustWork=TRUE);v4<-file.path(data_root,"diagnostics_v4_cross_dataset_validation");v5<-file.path(data_root,"diagnostics_v5_final_calibration");dir.create(v5,recursive=TRUE,showWarnings=FALSE)
replace_generated<-"--replace-generated-output"%in%commandArgs(trailingOnly=TRUE);out<-file.path(v5,"external_scrna_evidence_matrix_v2.csv");if(file.exists(out)&&!replace_generated)stop("Output exists: ",out)
manifest<-fread(file.path(v4,"final_external_scrna_dataset_manifest.csv"));old_evidence<-fread(file.path(v4,"external_scrna_evidence_matrix.csv"))[,.(dataset_id,n_high_confidence_macrophages)];spp1rep<-fread(file.path(v5,"macrophage_spp1_reproducibility_by_dataset.csv"));state_rep<-fread(file.path(v5,"macrophage_state_reproducibility_calibrated.csv"));presence<-fread(file.path(v5,"macrophage_state_presence_matrix.csv"))
agg<-presence[,.(n_evaluable_samples=sum(evaluable),n_present_samples=sum(state_presence=="PRESENT"),presence_status=if(sum(evaluable)==0)"NOT_EVALUABLE"else if(any(state_presence=="PRESENT"))"PRESENT"else"ABSENT_OR_LOW",relative_enrichment_status=if(sum(evaluable)==0)"NOT_EVALUABLE"else if(any(relative_enrichment=="RELATIVELY_ENRICHED"))"RELATIVELY_ENRICHED_IN_SUBSET"else"NO_RELATIVE_ENRICHMENT_AT_0.60"),by=.(dataset_id,state)]
repwide<-dcast(state_rep,dataset_id~state,value.var="reproducibility_status");preswide<-dcast(agg,dataset_id~state,value.var="presence_status");enrwide<-dcast(agg,dataset_id~state,value.var="relative_enrichment_status")
setnames(repwide,c("SPP1","C1QC","FOLR2"),paste0(c("SPP1","C1QC","FOLR2"),"_reproducibility_status"));setnames(preswide,c("SPP1","C1QC","FOLR2"),paste0(c("SPP1","C1QC","FOLR2"),"_presence_status"));setnames(enrwide,c("SPP1","C1QC","FOLR2"),paste0(c("SPP1","C1QC","FOLR2"),"_relative_enrichment_status"))
ctx<-fread(file.path(v4,"spp1_cd44_itgb1_context_by_sample.csv"));ctx[,context_name:="SPP1-associated epithelial CD44/ITGB1 context"];ctx[,receiver_interpretation:="Broad Epithelial receiver; not uniformly CNV-confirmed malignant"]
keepctx<-c("dataset_id","patient_id","sample_id","n_macrophages","evaluable","n_high_confidence_epithelial","receiver_evaluable","context_evaluable","SPP1_positive_fraction","SPP1_high_macrophage_fraction","SPP1_program_median_percentile","CD44_average_expression","CD44_positive_fraction","ITGB1_average_expression","ITGB1_positive_fraction","CD44_ITGB1_copositive_fraction","context_name","receiver_interpretation")
fwrite(ctx[,..keepctx],file.path(v5,"epithelial_receiver_context_by_sample.csv"),na="NA")
ctxagg<-ctx[,.(n_context_samples=sum(context_evaluable),epithelial_receiver_available=any(receiver_evaluable),median_CD44_positive_fraction=median(CD44_positive_fraction[receiver_evaluable],na.rm=TRUE),median_ITGB1_positive_fraction=median(ITGB1_positive_fraction[receiver_evaluable],na.rm=TRUE),median_dual_positive_fraction=median(CD44_ITGB1_copositive_fraction[receiver_evaluable],na.rm=TRUE)),by=dataset_id]
e<-Reduce(function(x,y)merge(x,y,by="dataset_id",all.x=TRUE),list(manifest,old_evidence,repwide,preswide,enrwide));e<-merge(e,ctxagg,by="dataset_id",all.x=TRUE);e<-merge(e,spp1rep[,.(dataset_id,n_evaluable_patients)],by="dataset_id",all.x=TRUE)
e[dataset_id=="GSE158722",evidence_level:=ifelse(SPP1_reproducibility_status=="REPLICATED","INDEPENDENT_REPLICATION","INCONCLUSIVE")]
e[,epithelial_receiver_available:=fifelse(is.na(epithelial_receiver_available),FALSE,epithelial_receiver_available)]
receiver_status<-function(avail,x){fcase(!avail,"NOT_AVAILABLE",is.finite(x)&x>=.10,"SUPPORTED",is.finite(x)&x>0,"DETECTED_LOW",default="NOT_DETECTED")}
e[,CD44_receiver_status:=receiver_status(epithelial_receiver_available,median_CD44_positive_fraction)];e[,ITGB1_receiver_status:=receiver_status(epithelial_receiver_available,median_ITGB1_positive_fraction)];e[,dual_positive_receiver_status:=receiver_status(epithelial_receiver_available,median_dual_positive_fraction)]
e[,sender_receiver_context_status:=fcase(n_context_samples>=6,"ELIGIBLE_FOR_SAMPLE_LEVEL_CORRELATION",n_context_samples>0,"DESCRIPTIVE_COEXISTENCE",default="NOT_EVALUABLE")]
e[,eligible_for_tumor_context_analysis:=dataset_id%in%c("GSE154600","GSE158722","GSE147082")&epithelial_receiver_available&n_context_samples>0]
e[,`:=`(supports_spp1_cross_patient_presence=SPP1_reproducibility_status=="REPLICATED",supports_c1qc_cross_patient_presence=C1QC_reproducibility_status=="REPLICATED",supports_folr2_cross_patient_presence=FOLR2_reproducibility_status=="REPLICATED",supports_relative_spp1_enrichment=SPP1_relative_enrichment_status=="RELATIVELY_ENRICHED_IN_SUBSET")]
e[,main_limitation:=fcase(dataset_id=="GSE158722","Only two evaluable patients and one evaluable positive patient; most timepoints have fewer than 20 high-confidence macrophages",dataset_id=="GSE147082","Sensitivity cohort; epithelial receiver is broad-lineage rather than uniformly CNV-confirmed malignant",dataset_id=="GSE151214","Normal reference only; excluded from tumor context effects",dataset_id=="GSE154763","Author-annotated normalized-expression myeloid reference; no epithelial receiver",default="Five patient units; receiver co-occurrence remains descriptive")]
keep<-c("dataset_id","dataset_role","evidence_level","n_total_cells","n_high_confidence_macrophages","n_evaluable_patients","SPP1_presence_status","SPP1_reproducibility_status","SPP1_relative_enrichment_status","C1QC_presence_status","C1QC_reproducibility_status","FOLR2_presence_status","FOLR2_reproducibility_status","epithelial_receiver_available","CD44_receiver_status","ITGB1_receiver_status","dual_positive_receiver_status","sender_receiver_context_status","eligible_for_tumor_context_analysis","supports_spp1_cross_patient_presence","supports_c1qc_cross_patient_presence","supports_folr2_cross_patient_presence","supports_relative_spp1_enrichment","main_limitation")
if("eligible_for_primary_conclusion"%in%names(e))e[,eligible_for_primary_conclusion:=NULL]
fwrite(e[,..keep],out,na="NA")
message("External evidence matrix v2 complete")
